packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - "@prisma/client"
  - "@parcel/watcher"
  - "@prisma/engines"
  - "@swc/core"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
allowBuilds:
  "@prisma/client": true
  "@parcel/watcher": true
  "@prisma/engines": true
  "@swc/core": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
